# Generated by Django 5.2 on 2025-04-12 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
