# Generated by Django 5.2 on 2025-04-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_delete_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimePasswordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=200)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('tried', models.PositiveBigIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
